### ISSUE TITLE
Issue with setting profile privacy

### ISSUE THREAD

**Issue by marcusjk** [socialveo/socialveo-issues-tracking#25]
language settings not working won't change

**Comment by andreakru** [comment]
At the moment it's installed only english.
I will add some other language so you can test.

**Comment by marcusjk** [comment]
Thank you so is that why when you try to change it to English united states an error pops up on top of the page

**Comment by andreakru** [comment]
I see.. But seem not caused by site language. Most probably you have not setup "Profile privacy"

<img width="544" alt="screen shot 2016-10-02 at 20 17 23" src="https://cloud.githubusercontent.com/assets/5359394/19022650/554ef0cc-88dd-11e6-84f1-d4aefb757ce4.png">

There is a generic error message when this setting is not set up.

We will improve this.

Thanks for report.

**Comment by marcusjk** [comment]
you where right profile privacy was not set

**Comment by andreakru** [comment]
This should be fixed now, added default privacy to "Public profile"
