### ISSUE TITLE
sharing

### ISSUE THREAD

**Issue by wlongdonstudio** [socialveo/socialveo-issues-tracking#36]
can't share information to group or page on facebook from a mobile only from desktop

**Comment by andreakru** [comment]
I just test with iphone and I was able to share to facebook.
Can you give me more details of issues?

**Comment by wlongdonstudio** [comment]
Using Android I'm not seeing the drop down option to share to group or page only share to my Facebook wall.

**Comment by wlongdonstudio** [comment]
https://www.dropbox.com/s/3juteqyxf2nckf1/Screenshot_20161227-220850.png?dl=0

**Comment by andreakru** [comment]
I understand only now what you mean.
I have to investigate why is not display the dropdown in mobile, because using website is display:

<img width="640" alt="screen shot 2016-12-28 at 15 42 25" src="https://cloud.githubusercontent.com/assets/5359394/21524170/5f3e57dc-cd14-11e6-8cb8-04b4df70fdc7.png">

However since this is facebook share API, if is missing mean that facebook don't provide this feature, since I don't find anything about on their doc. 

I don't have at the moment a smartphone to test this feature, but maybe you could test this:
https://developers.facebook.com/docs/plugins/share-button#example

If appear here, then we can check why not appear sharing post on socialveo.

**Comment by mervick** [comment]
Approved.
Tested on Android, facebook not show selectbox on their mobile version.
Seems it is a facebook bug/feature (https://google.com/search?q=facebook+share+to+group+mobile).
We can't do anything with it.
